export const statesInIndia = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry"
  ];
export const generalFields = [
    { name: "firstName", displayName: "First Name" },
    { name: "lastName", displayName: "Last Name" },
    { name: "email", displayName: "Email Address" },
    { name: "phoneNumber", displayName: "Phone Number" },
    { name: "password", displayName: "Password" },
  ];

export const addressFields = [
    { name: "houseNumber", displayName: "House Number" },
    { name: "street", displayName: "Street" },
    { name: "locality", displayName: "Locality" },
    { name: "pinCode", displayName: "Zip Code" },
    { name: "city", displayName: "City" },
  ];