export const QUERY_KEYS = {
    STATISTICS: "statistics",
    USER_DATA: "user-data",
    USER:"user",
    INDIVIDUAL_USER:"individual-user",
    ADDRESS:"address",
    ORDER:"order",
    INDIVIDUAL_ORDER:"individual-order",
    LOGOUT:"logout",
    ORDER_HISTORY:"order-history",
    JUNK_DETAILS: "junk-data",
    INDIVIDUAL_JUNK_DETAILS: "individual-junk-details",
    MERCHANT_STATISTICS:"merchant-statistics",
    MERCHANT_EXPENSES:"merchant-expenses",
    AVAILABLE_ORDERS:"available-orders",
    APPLIED_ORDERS:"applied-orders",
    PENDING_ORDERS:"pending-orders",
    MERCHANT_ORDER_DETAILS_WHICH_ARE_INTERESTED_FOR_A_PERTICULAR_ORDER:"merchant-order-details-which-are-interested-for-a-perticular-order",
    USER_REWARDS:"user-rewards",
    Specififc_ORDER_DETAILS:"specific-order-details",
    SPECIFIC_USER_DETAILS:"specific-user-details",
    JUNK_DATA: "junk-data",
    REWARDS:"rewards",
    ADMIN_STATISTICS:"admin-statistics",
    ADMIN_FILTER_ORDER:"admin-filter-order",
    HOMEPAGE_STATISTICS:"homepage_statistics",
    SPECIFIC_ORDER_DETAILS:"specific-order-details",
  } as const;
  